apiVersion: v1
kind: Secret
metadata:
    name: blog-secrets
    namespace: blog-app
type: Opaque
stringData:
    MONGODB_ATLAS_URL: "your_mongodb_url_here"
    SUPABASE_DATABASE_URL: "your_supabase_url_here"
    JWT_ACCESS_SECRET: "your_jwt_access_secret_here"
    JWT_REFRESH_SECRET: "your_jwt_refresh_secret_here"
    AWS_ACCESS_KEY_ID: "your_aws_key_id_here"
    AWS_SECRET_ACCESS_KEY: "your_aws_secret_key_here"
    AWS_BUCKET_NAME: "your_s3_bucket_name_here"
